baseURL = 'https://zhiblin.github.io/'
languageCode = 'en-us'
title = 'Diyouo'

theme = "hugo-theme-stack"

publishDir = "docs"

[pagination]
  pagerSize = 5

[params]
  mainSections = ["post"]

  [params.sidebar]
    emoji = "ðŸŒ™"
    subtitle = "A clean blog"
